export const LOGIN_USER_SUCESS = 'LOGIN_USER_SUCESS';
export const LOGIN_USER_ERR = 'LOGIN_USER_ERR';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const REGISTER_USER_SUCESS = 'REGISTER_USER_SUCESS';
export const REGISTER_USER_ERR = 'REGISTER_USER_ERR';
export const UPDATE_PASSWORD_SUCESS = 'UPDATE_PASSWORD_SUCESS';
export const UPDATE_PASSWORD_ERR = 'UPDATE_PASSWORD_ERR';
